# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Level2_Forecasting
                                 A QGIS plugin
 Calculate LD map using input features and forecasting model

 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-02-28
        copyright            : (C) 2021 by Sharad
        email                : email@email.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Level2_Forecasting class from file Level2_Forecasting.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .level2_forecasting import Level2_Forecasting
    return Level2_Forecasting(iface)
