# -*- coding: utf-8 -*-
"""
/***************************************************************************
 UserScenarios
                                 A QGIS plugin
 This plugin computes the difference in LD forecasting with and without user scenarios.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-03-06
        copyright            : (C) 2021 by Sharad Kumar Gupta
        email                : sharadgupta27@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load UserScenarios class from file UserScenarios.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .level_2_user_output import UserScenarios
    return UserScenarios(iface)
